[project]
name = "ingeinnova-backend"
version = "0.1.0"
description = "Servidor de Control y Gestión - INGEINNOVA"
readme = "README.md"
requires-python = ">=3.12"


dependencies = [
    "fastapi",
    "uvicorn[standard]",
    "sqlalchemy",
    "pydantic>=2.0",
    "python-multipart",
    "pydantic-settings",
    "psycopg[binary]>=3.3.3",
    "sqlmodel>=0.0.22",  # Movélo para acá
    "passlib[bcrypt]>=1.7.4",
    "pydantic-extra-types>=2.11.1",
    "phonenumbers>=9.0.30",
]


[dependency-groups]
dev = [
    "pytest>=8.0.0",
    "httpx>=0.28.1",
    "mypy>=1.20.0",
    "ruff>=0.15.12",
]
